apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: sushavonproductapi 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sushavonproductapi 
    spec:
      containers:
        - name: sushavonproductapi 
          image: pwccontainerregistry.azurecr.io/sushavonproductapi
          ports:
          - containerPort: 80